name = "SimulationBasedCalibration"
uuid = "84405b40-1b58-4881-906f-8add004fb729"
authors = ["Kiante Fernandez"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
